"use client";

import { useEffect, useState } from "react";
import { Sparkles, Loader2, Volume2, RotateCw } from "lucide-react";
import type { DashboardState } from "@/lib/state-types";

type Summary = {
  headline?: string;
  yesterday_line?: string;
  trend_line?: string;
  funnel_insight?: string;
  ads_to_watch?: string[];
  recommended_action?: string;
  on_track?: "yes" | "no" | "too early" | string;
  on_track_reason?: string;
};

function tryParse(text: string | null): Summary | null {
  if (!text) return null;
  const m = text.match(/\{[\s\S]*\}/);
  if (!m) return null;
  try {
    return JSON.parse(m[0]) as Summary;
  } catch {
    return null;
  }
}

function speak(text: string) {
  if (typeof window === "undefined" || !("speechSynthesis" in window)) return;
  window.speechSynthesis.cancel();
  const utter = new SpeechSynthesisUtterance(text);
  utter.rate = 1.05;
  utter.pitch = 1;
  window.speechSynthesis.speak(utter);
}

export function AISummaryPanel({ state }: { state: DashboardState | null }) {
  const [text, setText] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  function reload(forceState: DashboardState | null) {
    if (!forceState) return;
    setLoading(true);
    setErr(null);
    fetch("/api/insights/summary", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(forceState),
    })
      .then((r) => r.json())
      .then((json) => {
        setText(json.summary || null);
        if (json.error) setErr(json.summary);
      })
      .catch((e) => setErr(String(e)))
      .finally(() => setLoading(false));
  }

  useEffect(() => {
    if (!state) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    reload(state);
  }, [state]);

  const parsed = tryParse(text);

  const fullSpoken = parsed
    ? [parsed.headline, parsed.yesterday_line, parsed.trend_line, parsed.funnel_insight, parsed.recommended_action]
        .filter(Boolean)
        .join(" ")
    : "";

  return (
    <section className="rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/5 via-card to-card p-6 mb-6 relative overflow-hidden">
      <div className="absolute -top-12 -right-12 w-40 h-40 rounded-full bg-primary/10 blur-3xl pointer-events-none" />

      <div className="flex items-center justify-between mb-4 relative">
        <div className="flex items-center gap-2">
          <div className="w-9 h-9 rounded-lg bg-primary/15 flex items-center justify-center">
            <Sparkles className="w-5 h-5 text-primary" />
          </div>
          <div>
            <div className="text-xs uppercase tracking-wider text-muted-foreground font-medium">AI Daily Briefing</div>
            <div className="text-[10px] text-muted-foreground">Generated by Claude from today&apos;s campaign state</div>
          </div>
          {loading && <Loader2 className="w-3.5 h-3.5 animate-spin ml-2 text-primary" />}
        </div>

        <div className="flex items-center gap-1.5">
          {parsed && fullSpoken && (
            <button
              onClick={() => speak(fullSpoken)}
              className="text-xs px-2.5 py-1.5 rounded-md border border-border bg-card hover:bg-muted/60 flex items-center gap-1.5 transition-colors"
              title="Read briefing aloud"
            >
              <Volume2 className="w-3.5 h-3.5" />
              Listen
            </button>
          )}
          <button
            onClick={() => reload(state)}
            className="text-xs p-1.5 rounded-md border border-border bg-card hover:bg-muted/60 transition-colors"
            title="Regenerate briefing"
            disabled={loading}
          >
            <RotateCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          </button>
        </div>
      </div>

      {err && !parsed && <p className="text-sm text-destructive relative">{err}</p>}

      {!loading && !parsed && !err && (
        <p className="text-sm text-muted-foreground relative">No AI briefing yet. Hit refresh after the campaign goes live.</p>
      )}

      {parsed && (
        <div className="space-y-4 relative">
          {parsed.headline && (
            <h2 className="text-xl font-semibold leading-snug">{parsed.headline}</h2>
          )}

          <div className="grid sm:grid-cols-2 gap-3 text-sm">
            {parsed.yesterday_line && <p className="text-foreground/90 leading-relaxed">{parsed.yesterday_line}</p>}
            {parsed.trend_line && <p className="text-foreground/90 leading-relaxed">{parsed.trend_line}</p>}
            {parsed.funnel_insight && <p className="text-foreground/90 leading-relaxed sm:col-span-2">{parsed.funnel_insight}</p>}
          </div>

          {parsed.ads_to_watch && parsed.ads_to_watch.length > 0 && (
            <div className="text-sm">
              <span className="text-muted-foreground text-xs uppercase tracking-wide mr-2">Watch</span>
              {parsed.ads_to_watch.map((a, i) => (
                <span key={i} className="inline-block bg-muted/60 rounded px-2 py-0.5 text-xs mr-1.5 mb-1">{a}</span>
              ))}
            </div>
          )}

          {parsed.recommended_action && (
            <div className="rounded-xl bg-primary/10 border border-primary/30 p-4">
              <div className="text-[10px] uppercase tracking-wider text-primary mb-1 font-semibold">Action today</div>
              <p className="text-sm font-medium">{parsed.recommended_action}</p>
            </div>
          )}

          {parsed.on_track && (
            <div className="flex items-center gap-2 text-xs pt-1 border-t border-border">
              <span className="text-muted-foreground">On track?</span>
              <span
                className={
                  parsed.on_track === "yes"
                    ? "text-emerald-500 font-medium"
                    : parsed.on_track === "no"
                    ? "text-destructive font-medium"
                    : "text-amber-500 font-medium"
                }
              >
                {parsed.on_track}
              </span>
              {parsed.on_track_reason && <span className="text-muted-foreground">- {parsed.on_track_reason}</span>}
            </div>
          )}
        </div>
      )}
    </section>
  );
}
